services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - DOMAIN_NAME=${DOMAIN_NAME}
    secrets:
      - db_password
      - wp_admin_user
      - wp_admin_password
      - wp_admin_email
      - wp_regular_user
      - wp_regular_password
      - wp_regular_email
      - wp_auth_key
      - wp_secure_auth_key
      - wp_logged_in_key
      - wp_nonce_key
      - wp_auth_salt
      - wp_secure_auth_salt
      - wp_logged_in_salt
      - wp_nonce_salt

  mariadb:
    build:
      context: requirements/
      dockerfile: mariadb/Dockerfile
    container_name: mariadb
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    secrets:
      - db_root_password
      - db_password
    command: ["mysqld_safe", "--user=mysql"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_user:
    file: ../secrets/wp_admin_user.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_admin_email:
    file: ../secrets/wp_admin_email.txt
  wp_regular_user:
    file: ../secrets/wp_regular_user.txt
  wp_regular_password:
    file: ../secrets/wp_regular_password.txt
  wp_regular_email:
    file: ../secrets/wp_regular_email.txt
  wp_auth_key:
    file: ../secrets/wp_auth_key.txt
  wp_secure_auth_key:
    file: ../secrets/wp_secure_auth_key.txt
  wp_logged_in_key:
    file: ../secrets/wp_logged_in_key.txt
  wp_nonce_key:
    file: ../secrets/wp_nonce_key.txt
  wp_auth_salt:
    file: ../secrets/wp_auth_salt.txt
  wp_secure_auth_salt:
    file: ../secrets/wp_secure_auth_salt.txt
  wp_logged_in_salt:
    file: ../secrets/wp_logged_in_salt.txt
  wp_nonce_salt:
    file: ../secrets/wp_nonce_salt.txt

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind

networks:
  inception_network:
    driver: bridge